#Spring
server:
  port: 8080

spring:
  data:
    rest:
      base-path: /api

origins: /**
issuer: http://localhost:8081/realms/iotwatch

com:
  c4-soft:
    springaddons:
      oidc:
        cors:
          - path: /api/**
            allowed-origin-patterns: ${origins}
        ops:
          # as this is an array of issuers, we may define more than one Keycloak realm
          # or even completely different authorization servers (using other private claims for user roles)
          - iss: ${issuer}
            # for illustration purpose only: the default (iss) is probably a better option
            username-claim: preferred_username
            authorities:
              - path: $.realm_access.roles
                # for illustration purpose, the default is an empty string
                prefix: ROLE_
                # any valid JsonPath expression resolved to a list of strings is acceptable
              - path: $.resource_access.*.roles
        resourceserver:
          # default access rule is "isAuthenticated" except for the path matched here (allowed to anonymous requests)
          permit-all:
            - "/actuator/health/readiness"
            - "/actuator/health/liveness"
            - "/api-docs/**"
            - "/resources"
